# Part 1: Matrix Algebra with Python 

In [1]:
import numpy as np 
import os
# os.chdir('C:/Users/User/Desktop/BUS 705 - Statistics and Programming for BA/HW/Final Project')

In [2]:
# 1-1. Input the matrix A
A = np.array([[1, 2, 0], [1, 0, 3], [0, 0, 8]])
print(A)

[[1 2 0]
 [1 0 3]
 [0 0 8]]


In [3]:
# 1-2. Determine the determinant of A. Is A invertible? If so, determine the inverse. What's the determinant of the inverse?
# The determinant of A: -16 -> A is invertible.
print ("The determinant of A: %.2f " % np.linalg.det(A)) 
print ("A is invertible.")

The determinant of A: -16.00 
A is invertible.


In [4]:
# Inverse A
A_inv = np.linalg.inv(A)
print("The inverse of A : ")
print(A_inv)

The inverse of A : 
[[ 0.      1.     -0.375 ]
 [ 0.5    -0.5     0.1875]
 [ 0.      0.      0.125 ]]


In [5]:
# The determinant of the inverse: -0.0625
print ("The determinant of the inverse:" , np.linalg.det(A_inv))

The determinant of the inverse: -0.0625


In [6]:
# 1-3. Calculate X = A'A. Is X positive definite? 
A_trans = A.transpose()
X = np.dot(A_trans, A) 
print("Matrix X: ")
print(X)     

# Check whether all eigenvalues are positive
if np.all(np.linalg.eigvals(X)) > 0:
    print("\nX is positive definite.")   # X is positive definite.
else:
    print("\nX is not positive definite.") 

Matrix X: 
[[ 2  2  3]
 [ 2  4  0]
 [ 3  0 73]]

X is positive definite.


In [7]:
# 1-4. Determine the Cholesky decomposition of X.
print("Cholesky decomposition of X: ")
print(np.linalg.cholesky(X)) # lower-triangular Cholesky factor 

Cholesky decomposition of X: 
[[ 1.41421356  0.          0.        ]
 [ 1.41421356  1.41421356  0.        ]
 [ 2.12132034 -2.12132034  8.        ]]


In [8]:
# 1-5. Determine the eigenvalues and eigenvectors of X and show the matrix-diagonalized form of X.
EValue, EVector = np.linalg.eig(X)
print("Eigenvalues: ")
print(EValue)     # eigenvalues
print("\nEigenvectors: ")
print(EVector)    # eigenvectors

Eigenvalues: 
[73.1266379  0.673206   5.2001561]

Eigenvectors: 
[[-0.04217504 -0.85650564 -0.51441166]
 [-0.00122023  0.51491354 -0.85724125]
 [-0.99910949  0.03552649  0.02276163]]


In [9]:
# The matrix-diagonalized form of X
D = np.diag(EValue)   # EVector.dot(D).dot(EVector.transpose()) = X
print("The matrix-diagonalized form of X: ")
print(D)

The matrix-diagonalized form of X: 
[[73.1266379  0.         0.       ]
 [ 0.         0.673206   0.       ]
 [ 0.         0.         5.2001561]]
